import module namespace request = "http://www.28msec.com/modules/http-request";
import module namespace config = "http://apps.28.io/config";
[ {
    "Name" : "jpcrp030000-asr_e01225-000:LossOfInactiveFacilitiesEL",
    "Labels" : "http://"||request:server-name()||":"||request:server-port()||"/v1/_queries/public/api/labels.jq?_method=POST&token="||$config:test-token||"&concept=jpcrp030000-asr_e01225-000%3ALossOfInactiveFacilitiesEL&aid=S10028XL&role=http%3A%2F%2Fdisclosure.edinet-fsa.go.jp%2Frole%2Fjppfs%2Frol_ConsolidatedStatementOfIncome&format=&profile-name=japan",
    "Facts" : "http://"||request:server-name()||":"||request:server-port()||"/v1/_queries/public/api/facts.jq?_method=POST&token="||$config:test-token||"&xbrl:Concept=jpcrp030000-asr_e01225-000%3ALossOfInactiveFacilitiesEL&aid=S10028XL&format=&profile-name=japan&fiscalYear=ALL&fiscalPeriod=ALL&fiscalPeriodType=ALL",
    "Label" : "設備休止関連損失",
    "IsNillable" : true,
    "IsAbstract" : false,
    "PeriodType" : "duration",
    "Balance" : "debit",
    "SubstitutionGroup" : "xbrli:item",
    "DataType" : "xbrli:monetaryItemType",
    "BaseType" : "xbrli:monetary",
    "ClosestSchemaBuiltinType" : "xs:decimal",
    "IsTextBlock" : false,
    "ComponentRole" : "http://disclosure.edinet-fsa.go.jp/role/jppfs/rol_ConsolidatedStatementOfIncome",
    "ComponentLabel" : "連結損益計算書",
    "Archive" : "S10028XL"
  }, {
    "Name" : "jpfr-asr-e01225-000:LossOfInactiveFacilitiesEL",
    "Labels" : "http://"||request:server-name()||":"||request:server-port()||"/v1/_queries/public/api/labels.jq?_method=POST&token="||$config:test-token||"&concept=jpfr-asr-e01225-000%3ALossOfInactiveFacilitiesEL&aid=S000DR20&role=http%3A%2F%2Finfo.edinet-fsa.go.jp%2Fjp%2Ffr%2Fgaap%2Frole%2FNonConsolidatedStatementsOfIncome&format=&profile-name=japan",
    "Facts" : "http://"||request:server-name()||":"||request:server-port()||"/v1/_queries/public/api/facts.jq?_method=POST&token="||$config:test-token||"&xbrl:Concept=jpfr-asr-e01225-000%3ALossOfInactiveFacilitiesEL&aid=S000DR20&format=&profile-name=japan&fiscalYear=ALL&fiscalPeriod=ALL&fiscalPeriodType=ALL",
    "Label" : "設備休止関連損失",
    "IsNillable" : true,
    "IsAbstract" : false,
    "PeriodType" : "duration",
    "Balance" : "debit",
    "SubstitutionGroup" : "xbrli:item",
    "DataType" : "xbrli:monetaryItemType",
    "BaseType" : "xbrli:monetary",
    "ClosestSchemaBuiltinType" : "xs:decimal",
    "IsTextBlock" : false,
    "ComponentRole" : "http://info.edinet-fsa.go.jp/jp/fr/gaap/role/NonConsolidatedStatementsOfIncome",
    "ComponentLabel" : "損益計算書　財務諸表等規則様式第三号",
    "Archive" : "S000DR20"
  }, {
    "Name" : "jpfr-asr-e01225-000:LossOfInactiveFacilitiesEL",
    "Labels" : "http://"||request:server-name()||":"||request:server-port()||"/v1/_queries/public/api/labels.jq?_method=POST&token="||$config:test-token||"&concept=jpfr-asr-e01225-000%3ALossOfInactiveFacilitiesEL&aid=S000DR20&role=http%3A%2F%2Finfo.edinet-fsa.go.jp%2Fjp%2Ffr%2Fgaap%2Frole%2FConsolidatedStatementsOfIncome&format=&profile-name=japan",
    "Facts" : "http://"||request:server-name()||":"||request:server-port()||"/v1/_queries/public/api/facts.jq?_method=POST&token="||$config:test-token||"&xbrl:Concept=jpfr-asr-e01225-000%3ALossOfInactiveFacilitiesEL&aid=S000DR20&format=&profile-name=japan&fiscalYear=ALL&fiscalPeriod=ALL&fiscalPeriodType=ALL",
    "Label" : "設備休止関連損失",
    "IsNillable" : true,
    "IsAbstract" : false,
    "PeriodType" : "duration",
    "Balance" : "debit",
    "SubstitutionGroup" : "xbrli:item",
    "DataType" : "xbrli:monetaryItemType",
    "BaseType" : "xbrli:monetary",
    "ClosestSchemaBuiltinType" : "xs:decimal",
    "IsTextBlock" : false,
    "ComponentRole" : "http://info.edinet-fsa.go.jp/jp/fr/gaap/role/ConsolidatedStatementsOfIncome",
    "ComponentLabel" : "連結損益計算書　連結財務諸表規則様式第五号",
    "Archive" : "S000DR20"
  }, {
    "Name" : "jpcrp030000-asr_e01225-000:NotesRegardingTheLossOfInactiveFacilitiesTextBlock",
    "Labels" : "http://"||request:server-name()||":"||request:server-port()||"/v1/_queries/public/api/labels.jq?_method=POST&token="||$config:test-token||"&concept=jpcrp030000-asr_e01225-000%3ANotesRegardingTheLossOfInactiveFacilitiesTextBlock&aid=S10028XL&role=http%3A%2F%2Fdisclosure.edinet-fsa.go.jp%2Frole%2Fjpcrp%2Frol_NotesConsolidatedStatementOfIncome&format=&profile-name=japan",
    "Facts" : "http://"||request:server-name()||":"||request:server-port()||"/v1/_queries/public/api/facts.jq?_method=POST&token="||$config:test-token||"&xbrl:Concept=jpcrp030000-asr_e01225-000%3ANotesRegardingTheLossOfInactiveFacilitiesTextBlock&aid=S10028XL&format=&profile-name=japan&fiscalYear=ALL&fiscalPeriod=ALL&fiscalPeriodType=ALL",
    "Label" : "設備休止関連損失に関する注記",
    "IsNillable" : true,
    "IsAbstract" : false,
    "PeriodType" : "duration",
    "SubstitutionGroup" : "xbrli:item",
    "DataType" : "nonnum:textBlockItemType",
    "BaseType" : "xs:string",
    "ClosestSchemaBuiltinType" : "xs:string",
    "IsTextBlock" : true,
    "ComponentRole" : "http://disclosure.edinet-fsa.go.jp/role/jpcrp/rol_NotesConsolidatedStatementOfIncome",
    "ComponentLabel" : "連結損益計算書関係",
    "Archive" : "S10028XL"
  }, {
    "Name" : "jpcrp030000-asr_e01225-000:LossOfInactiveFacilitiesEL",
    "Labels" : "http://"||request:server-name()||":"||request:server-port()||"/v1/_queries/public/api/labels.jq?_method=POST&token="||$config:test-token||"&concept=jpcrp030000-asr_e01225-000%3ALossOfInactiveFacilitiesEL&aid=S10028XL&role=http%3A%2F%2Fdisclosure.edinet-fsa.go.jp%2Frole%2Fjppfs%2Frol_StatementOfIncome&format=&profile-name=japan",
    "Facts" : "http://"||request:server-name()||":"||request:server-port()||"/v1/_queries/public/api/facts.jq?_method=POST&token="||$config:test-token||"&xbrl:Concept=jpcrp030000-asr_e01225-000%3ALossOfInactiveFacilitiesEL&aid=S10028XL&format=&profile-name=japan&fiscalYear=ALL&fiscalPeriod=ALL&fiscalPeriodType=ALL",
    "Label" : "設備休止関連損失",
    "IsNillable" : true,
    "IsAbstract" : false,
    "PeriodType" : "duration",
    "Balance" : "debit",
    "SubstitutionGroup" : "xbrli:item",
    "DataType" : "xbrli:monetaryItemType",
    "BaseType" : "xbrli:monetary",
    "ClosestSchemaBuiltinType" : "xs:decimal",
    "IsTextBlock" : false,
    "ComponentRole" : "http://disclosure.edinet-fsa.go.jp/role/jppfs/rol_StatementOfIncome",
    "ComponentLabel" : "損益計算書",
    "Archive" : "S10028XL"
  } ]
