[ {
      "NetworkLabel" : "0001000 - Document - Document and Entity Information",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/DocumentAndEntityInformation",
      "Category" : "Document",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:StatementTable",
      "Disclosure" : "DocumentAndEntityInformation",
      "ReportElements" : 25,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 2,
      "LineItems" : 1,
      "Concepts" : 10,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "1001000 - Statement - CONDENSED CONSOLIDATED STATEMENTS OF INCOME",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/CondensedConsolidatedStatementsOfIncome",
      "Category" : "Statement",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:StatementTable",
      "Disclosure" : "IncomeStatement",
      "ReportElements" : 36,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 2,
      "LineItems" : 1,
      "Concepts" : 21,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "1002000 - Statement - CONDENSED CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/CondensedConsolidatedStatementsOfComprehensiveIncome",
      "Category" : "Statement",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:StatementTable",
      "Disclosure" : "StatementOfComprehensiveIncome",
      "ReportElements" : 24,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 2,
      "LineItems" : 1,
      "Concepts" : 8,
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "1003000 - Statement - CONDENSED CONSOLIDATED BALANCE SHEETS",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/CondensedConsolidatedBalanceSheets",
      "Category" : "Statement",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:StatementTable",
      "Disclosure" : "BalanceSheet",
      "ReportElements" : 56,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 2,
      "LineItems" : 1,
      "Concepts" : 36,
      "Abstracts" : 6
    }, {
      "NetworkLabel" : "1003500 - Statement - CONDENSED CONSOLIDATED BALANCE SHEETS Parentheticals",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/CondensedConsolidatedBalanceSheetsParentheticals",
      "Category" : "Statement",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:StatementTable",
      "Disclosure" : "BalanceSheetParenthetical",
      "ReportElements" : 21,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 2,
      "LineItems" : 1,
      "Concepts" : 6,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "1004000 - Statement - CONDENSED CONSOLIDATED STATEMENTS OF CASH FLOWS",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/CondensedConsolidatedStatementsOfCashFlows",
      "Category" : "Statement",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:StatementTable",
      "Disclosure" : "CashFlowStatement",
      "ReportElements" : 48,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 2,
      "LineItems" : 1,
      "Concepts" : 29,
      "Abstracts" : 5
    }, {
      "NetworkLabel" : "2101100 - Disclosure - Summary of Significant Accounting Policies",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/SummaryOfSignificantAccountingPolicies",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "SignificantAccountingPolicies",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 1,
      "Concepts" : 1,
      "Abstracts" : 0
    }, {
      "NetworkLabel" : "2102100 - Disclosure - Acquisitions and Divestitures",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/AcquisitionsAndDivestitures",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "BusinessCombinationDisclosure",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2103100 - Disclosure - Investments",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/Investments",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2104100 - Disclosure - Inventories",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/Inventories",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "InventoryDisclosure",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 1,
      "Concepts" : 1,
      "Abstracts" : 0
    }, {
      "NetworkLabel" : "2105100 - Disclosure - Hedging Transactions and Derivative Financial Instruments",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/HedgingTransactionsAndDerivativeFinancialInstruments",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2106100 - Disclosure - Debt and Borrowing Arrangements",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/DebtAndBorrowingArrangements",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "DebtDisclosure",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2107100 - Disclosure - Commitments and Contingencies",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/CommitmentsAndContingencies",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "ContingenciesDisclosure",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2108100 - Disclosure - Comprehensive Income",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/ComprehensiveIncome",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2109100 - Disclosure - Changes in Equity",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/ChangesInEquity",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2110100 - Disclosure - Significant Operating and Nonoperating Items",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/SignificantOperatingAndNonoperatingItems",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2111100 - Disclosure - Productivity, Integration and Restructuring Initiatives",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/ProductivityIntegrationAndRestructuringInitiatives",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 1,
      "Concepts" : 1,
      "Abstracts" : 0
    }, {
      "NetworkLabel" : "2112100 - Disclosure - Pension and Other Postretirement Benefit Plans",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/PensionAndOtherPostretirementBenefitPlans",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "PostemploymentBenefits",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2113100 - Disclosure - Income Taxes",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/IncomeTaxes",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "IncomeTaxDisclosure",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2114100 - Disclosure - Fair Value Measurements",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/FairValueMeasurements",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "FairValueMeasurementsOther",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2115100 - Disclosure - Operating Segments",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/OperatingSegments",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2302301 - Disclosure - Acquisitions and Divestitures (Tables)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/AcquisitionsAndDivestituresTables",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "BusinessCombinationDisclosure",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2303301 - Disclosure - Investments (Tables)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/InvestmentsTables",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 17,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 5,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2304301 - Disclosure - Inventories (Tables)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/InventoriesTables",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "InventoryDisclosure",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 1,
      "Concepts" : 1,
      "Abstracts" : 0
    }, {
      "NetworkLabel" : "2305301 - Disclosure - Hedging Transactions and Derivative Financial Instruments (Tables)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/HedgingTransactionsAndDerivativeFinancialInstrumentsTables",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 18,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 6,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2308301 - Disclosure - Comprehensive Income (Tables)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/ComprehensiveIncomeTables",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 15,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 3,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2309301 - Disclosure - Changes in Equity (Tables)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/ChangesInEquityTables",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2311301 - Disclosure - Productivity, Integration and Restructuring Initiatives (Tables)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/ProductivityIntegrationAndRestructuringInitiativesTables",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "us-gaap:ScheduleOfRestructuringAndRelatedCostsTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 16,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 2,
      "LineItems" : 1,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2312301 - Disclosure - Pension and Other Postretirement Benefit Plans (Tables)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/PensionAndOtherPostretirementBenefitPlansTables",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "PostemploymentBenefits",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2313301 - Disclosure - Income Taxes (Tables)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/IncomeTaxesTables",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "IncomeTaxDisclosure",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2314301 - Disclosure - Fair Value Measurements (Tables)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/FairValueMeasurementsTables",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "FairValueMeasurementsOther",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 0,
      "Concepts" : 1,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2315301 - Disclosure - Operating Segments (Tables)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/OperatingSegmentsTables",
      "Category" : "Disclosure",
      "SubCategory" : "TextBlockLevel1To3",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 13,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 1,
      "Concepts" : 1,
      "Abstracts" : 0
    }, {
      "NetworkLabel" : "2402402 - Disclosure - Acquisitions and Divestitures (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/AcquisitionsAndDivestituresDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "ko:ScheduleOfBusinessAcquisitionsAndInvestmentActivityTable",
      "Disclosure" : "BusinessCombinationDisclosure",
      "ReportElements" : 23,
      "Tables" : 1,
      "Axis" : 11,
      "Members" : 6,
      "LineItems" : 1,
      "Concepts" : 3,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2402403 - Disclosure - Acquisitions and Divestitures (Details 2)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/AcquisitionsAndDivestituresDetails2",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "ko:DisposalGroupNotDiscontinuedOperationsTable",
      "Disclosure" : "BusinessCombinationDisclosure",
      "ReportElements" : 38,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 5,
      "LineItems" : 1,
      "Concepts" : 20,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2403402 - Disclosure - Investments (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/InvestmentsDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:ScheduleOfTradingSecuritiesAndOtherTradingAssetsTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 21,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 3,
      "LineItems" : 2,
      "Concepts" : 4,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2403403 - Disclosure - Investments (Details 2)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/InvestmentsDetails2",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:ScheduleOfAvailableForSaleSecuritiesTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 21,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 4,
      "LineItems" : 1,
      "Concepts" : 4,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2403405 - Disclosure - Investments (Details 4)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/InvestmentsDetails4",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:FairValueByBalanceSheetGroupingTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 28,
      "Tables" : 1,
      "Axis" : 11,
      "Members" : 5,
      "LineItems" : 1,
      "Concepts" : 9,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2403406 - Disclosure - Investments (Details 5)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/InvestmentsDetails5",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:ScheduleOfHeldToMaturitySecuritiesTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 28,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 3,
      "LineItems" : 2,
      "Concepts" : 11,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2404402 - Disclosure - Inventories (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/InventoriesDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "InventoryDisclosure",
      "ReportElements" : 17,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 1,
      "Concepts" : 4,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2405402 - Disclosure - Hedging Transactions and Derivative Financial Instruments (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/HedgingTransactionsAndDerivativeFinancialInstrumentsDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:FairValuesDerivativesBalanceSheetLocationByDerivativeContractTypeByHedgingDesignationTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 34,
      "Tables" : 1,
      "Axis" : 11,
      "Members" : 11,
      "LineItems" : 2,
      "Concepts" : 8,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2405403 - Disclosure - Hedging Transactions and Derivative Financial Instruments (Details 2)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/HedgingTransactionsAndDerivativeFinancialInstrumentsDetails2",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:DerivativeInstrumentsGainLossByHedgingRelationshipByIncomeStatementLocationByDerivativeInstrumentRiskTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 46,
      "Tables" : 1,
      "Axis" : 12,
      "Members" : 20,
      "LineItems" : 1,
      "Concepts" : 11,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2406402 - Disclosure - Debt and Borrowing Arrangements (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/DebtAndBorrowingArrangementsDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:DebtInstrumentTable",
      "Disclosure" : "DebtDisclosure",
      "ReportElements" : 26,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 8,
      "LineItems" : 1,
      "Concepts" : 5,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2407402 - Disclosure - Commitments and Contingencies (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/CommitmentsAndContingenciesDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:LossContingenciesTable",
      "Disclosure" : "ContingenciesDisclosure",
      "ReportElements" : 33,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 5,
      "LineItems" : 1,
      "Concepts" : 12,
      "Abstracts" : 4
    }, {
      "NetworkLabel" : "2408402 - Disclosure - Comprehensive Income (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/ComprehensiveIncomeDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:StatementTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 95,
      "Tables" : 1,
      "Axis" : 12,
      "Members" : 17,
      "LineItems" : 1,
      "Concepts" : 46,
      "Abstracts" : 18
    }, {
      "NetworkLabel" : "2409402 - Disclosure - Changes in Equity (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/ChangesInEquityDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:StatementTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 31,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 8,
      "LineItems" : 1,
      "Concepts" : 9,
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2410401 - Disclosure - Significant Operating and Nonoperating Items (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/SignificantOperatingAndNonoperatingItemsDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "ko:ComponentOfOtherOperatingAndNonoperatingCostAndExpenseTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 45,
      "Tables" : 1,
      "Axis" : 14,
      "Members" : 16,
      "LineItems" : 1,
      "Concepts" : 7,
      "Abstracts" : 6
    }, {
      "NetworkLabel" : "2411402 - Disclosure - Productivity, Integration and Restructuring Initiatives (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/ProductivityIntegrationAndRestructuringInitiativesDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:ScheduleOfRestructuringAndRelatedCostsTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 29,
      "Tables" : 1,
      "Axis" : 11,
      "Members" : 8,
      "LineItems" : 1,
      "Concepts" : 6,
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2412402 - Disclosure - Pension and Other Postretirement Benefit Plans (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/PensionAndOtherPostretirementBenefitPlansDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:ScheduleOfDefinedBenefitPlansDisclosuresTable",
      "Disclosure" : "PostemploymentBenefits",
      "ReportElements" : 25,
      "Tables" : 1,
      "Axis" : 10,
      "Members" : 4,
      "LineItems" : 1,
      "Concepts" : 8,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2413402 - Disclosure - Income Taxes (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/IncomeTaxesDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:IncomeTaxContingencyTable",
      "Disclosure" : "IncomeTaxDisclosure",
      "ReportElements" : 45,
      "Tables" : 1,
      "Axis" : 12,
      "Members" : 10,
      "LineItems" : 1,
      "Concepts" : 18,
      "Abstracts" : 3
    }, {
      "NetworkLabel" : "2414402 - Disclosure - Fair Value Measurements (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/FairValueMeasurementsDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "ko:FairValueAssetsAndLiabilitiesMeasuredOnRecurringBasisTable",
      "Disclosure" : "FairValueMeasurementsOther",
      "ReportElements" : 32,
      "Tables" : 1,
      "Axis" : 11,
      "Members" : 12,
      "LineItems" : 1,
      "Concepts" : 6,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2414403 - Disclosure - Fair Value Measurements (Details 2)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/FairValueMeasurementsDetails2",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:FairValueAssetsAndLiabilitiesMeasuredOnRecurringAndNonrecurringBasisTable",
      "Disclosure" : "FairValueMeasurementsOther",
      "ReportElements" : 19,
      "Tables" : 1,
      "Axis" : 11,
      "Members" : 3,
      "LineItems" : 1,
      "Concepts" : 2,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2414404 - Disclosure - Fair Value Measurements (Details 3)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/FairValueMeasurementsDetails3",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "xbrl28:ImpliedTable",
      "Disclosure" : "FairValueMeasurementsOther",
      "ReportElements" : 15,
      "Tables" : 1,
      "Axis" : 9,
      "Members" : 1,
      "LineItems" : 1,
      "Concepts" : 2,
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2415402 - Disclosure - Operating Segments (Details)",
      "NetworkIdentifier" : "http://www.thecoca-colacompany.com/role/OperatingSegmentsDetails",
      "Category" : "Disclosure",
      "SubCategory" : "Detail",
      "Table" : "us-gaap:ScheduleOfSegmentReportingInformationBySegmentTable",
      "Disclosure" : "UncategorizedInformation",
      "ReportElements" : 49,
      "Tables" : 1,
      "Axis" : 13,
      "Members" : 18,
      "LineItems" : 1,
      "Concepts" : 14,
      "Abstracts" : 2
    } ]
